// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": {
    "title": "Accueil",
    "description": "Welcome to our home page",
    "page": {
      "header-section": {
        "title": "Transformez vos idées en produits que vos utilisateurs adorent",
        "description": "Product designer spécialisé dans la simplification des expériences SaaS + formateur pour les équipes qui veulent créer l&#39;évidence plutôt que la complexité",
        "cta": "Discutons 👋",
        "cta-2": "Voir mes projets client 💡"
      }
    }
  },
  "about": {
    "title": "A propos",
    "description": "Welcome to our about page"
  },
  "thoughts": {
    "description": "Read the latest news from our company",
    "title": "My awesome blog",
    "back": "Back to blog"
  },
  "contact": {
    "title": "Dire bonjour 👋",
    "description": "We are here to help you. Please use the form below to get in touch with us.",
    "page": {
      "badge": "Problem Solver & Your SaaS Product designer ❣️",
      "title": "Transforme tes idées en produits que tes utilisateurs adorent 🦄",
      "form": {
        "notifications": {
          "error": "We are sorry, but we were unable to send your message. Please try again later.",
          "success": "Your message has been sent successfully. We will get back to you as soon as possible."
        },
        "submit": "Recevoir !🦄"
      }
    }
  },
  "newsletter": {
    "title": "Get early access",
    "description": "Be among the first to get access to supastarter.nextjs.",
    "page": {
      "badge": "Pour les développeurs freelances qui galèrent à trouver des clients.",
      "title": "Trouve des clients en continu grâce à la méthode Tsunami 🌊",
      "desc": "Je te montre comment utiliser l&#39;IA et l&#39;AUTOMATISATION pour trouver des missions en boucle."
    },
    "email": "Email",
    "hints": {
      "error": {
        "message": "Could not subscribe to newsletter. Please try again later."
      },
      "success": {
        "message": "Thank you for subscribing to our newsletter. We will keep you posted.",
        "title": "Subscribed"
      }
    },
    "submit": "Subscribe",
    "subtitle": "Be among the first to get access to supastarter.nextjs."
  },
  "common": {
    "confirmation": {
      "cancel": "Annuler",
      "confirm": "Confirmer"
    },
    "menu": {
      "home": "Accueil",
      "about": "A propos",
      "thoughts": "Réflexions",
      "hub": "Hub",
      "projects": "Projets",
      "contact": "Contact",
      "newsletter": "Newsletter"
    },
    "actions": {
      "continue": "Continuer",
      "verify": "Vérifier"
    }
  },
  "mail": {
    "common": {
      "openLinkInBrowser": "If you want to open the link in a different browser than your default one, copy and paste this link:",
      "otp": "One-time password",
      "useLink": "or use the following link:"
    },
    "emailVerification": {
      "body": "Hey,\nplease click the link below to verify this new email address.",
      "confirmEmail": "Verify email",
      "subject": "Verify your email"
    },
    "forgotPassword": {
      "body": "Hey,\nyou requested a password reset.\n\nClick the button below to reset your password.",
      "resetPassword": "Reset password",
      "subject": "Reset your password"
    },
    "magicLink": {
      "body": "Hey,\nyou requested a login email from supastarter.\n\nClick the link below to login.",
      "login": "Login",
      "subject": "Login to supastarter"
    },
    "newUser": {
      "body": "Hey,\nthanks for signing up for supastarter.\n\nTo start using our app, please confirm your email address by clicking the link below.",
      "confirmEmail": "Confirm email",
      "subject": "Confirm your email"
    },
    "newsletterSignup": {
      "body": "Thank you for signing up for the supastarter newsletter. We will keep you updated with the latest news and updates.",
      "subject": "Welcome to our newsletter"
    },
    "organizationInvitation": {
      "body": "You have been invited to join the organization {organizationName}. Click the button below or copy and paste the link into your browser of choice to accept the invitation and join the organization.",
      "headline": "Join the organization {organizationName}",
      "join": "Join the organization",
      "subject": "You have been invited to join an organization"
    }
  },
  "start": {
    "subtitle": "See the latest stats of your awesome business.",
    "welcome": "Welcome {name}!"
  },
  "zod": {
    "errors": {
      "invalid_arguments": "Invalid function arguments",
      "invalid_date": "Invalid date",
      "invalid_enum_value": "Invalid enum value. Expected {- options}, received '{received}'",
      "invalid_intersection_types": "Intersection results could not be merged",
      "invalid_literal": "Invalid literal value, expected {expected}",
      "invalid_return_type": "Invalid function return type",
      "invalid_string": {
        "cuid": "Invalid {validation}",
        "datetime": "Invalid {validation}",
        "email": "Invalid {validation}",
        "endsWith": "Invalid input: must end with \"{endsWith}\"",
        "regex": "Invalid",
        "startsWith": "Invalid input: must start with \"{startsWith}\"",
        "url": "Invalid {validation}",
        "uuid": "Invalid {validation}"
      },
      "invalid_type": "Expected {expected}, received {received}",
      "invalid_type_received_undefined": "Required",
      "invalid_union": "Invalid input",
      "invalid_union_discriminator": "Invalid discriminator value. Expected {- options}",
      "not_finite": "Number must be finite",
      "not_multiple_of": "Number must be a multiple of {multipleOf}",
      "too_big": {
        "array": {
          "exact": "Array must contain exactly {maximum} element(s)",
          "inclusive": "Array must contain at most {maximum} element(s)",
          "not_inclusive": "Array must contain less than {maximum} element(s)"
        },
        "date": {
          "exact": "Date must be exactly {- maximum, datetime}",
          "inclusive": "Date must be smaller than or equal to {- maximum, datetime}",
          "not_inclusive": "Date must be smaller than {- maximum, datetime}"
        },
        "number": {
          "exact": "Number must be exactly {maximum}",
          "inclusive": "Number must be less than or equal to {maximum}",
          "not_inclusive": "Number must be less than {maximum}"
        },
        "set": {
          "exact": "Invalid input",
          "inclusive": "Invalid input",
          "not_inclusive": "Invalid input"
        },
        "string": {
          "exact": "String must contain exactly {maximum} character(s)",
          "inclusive": "String must contain at most {maximum} character(s)",
          "not_inclusive": "String must contain under {maximum} character(s)"
        }
      },
      "too_small": {
        "array": {
          "exact": "Array must contain exactly {minimum} element(s)",
          "inclusive": "Array must contain at least {minimum} element(s)",
          "not_inclusive": "Array must contain more than {minimum} element(s)"
        },
        "date": {
          "exact": "Date must be exactly {- minimum, datetime}",
          "inclusive": "Date must be greater than or equal to {- minimum, datetime}",
          "not_inclusive": "Date must be greater than {- minimum, datetime}"
        },
        "number": {
          "exact": "Number must be exactly {minimum}",
          "inclusive": "Number must be greater than or equal to {minimum}",
          "not_inclusive": "Number must be greater than {minimum}"
        },
        "set": {
          "exact": "Invalid input",
          "inclusive": "Invalid input",
          "not_inclusive": "Invalid input"
        },
        "string": {
          "exact": "String must contain exactly {minimum} character(s)",
          "inclusive": "String must contain at least {minimum} character(s)",
          "not_inclusive": "String must contain over {minimum} character(s)"
        }
      },
      "unrecognized_keys": "Unrecognized key(s) in object: {- keys}"
    },
    "types": {
      "array": "array",
      "bigint": "bigint",
      "boolean": "boolean",
      "date": "date",
      "float": "float",
      "function": "function",
      "integer": "integer",
      "map": "map",
      "nan": "nan",
      "never": "never",
      "null": "null",
      "number": "number",
      "object": "object",
      "promise": "promise",
      "set": "set",
      "string": "string",
      "symbol": "symbol",
      "undefined": "undefined",
      "unknown": "unknown",
      "void": "void"
    },
    "validations": {
      "cuid": "cuid",
      "cuid2": "cuid2",
      "datetime": "datetime",
      "email": "email",
      "emoji": "emoji",
      "ip": "up",
      "regex": "regex",
      "ulid": "ulid",
      "url": "url",
      "uuid": "uuid"
    }
  }
};
export default messages;