/**
 * Map a range of numbers to an array.
 *
 * @param {number} n - The number of elements in the array.
 * @param {function} [fn] - The function to apply to each element.
 *
 * @returns {any[]} An array of elements generated by the function.
 *
 * @example
 * rangeMap({n: 5}); // returns [0, 1, 2, 3, 4]
 *
 * @example
 * rangeMap({n: 5, fn: (i) => i * 2}); // returns [0, 2, 4, 6, 8]
 *
 * @example
 * rangeMap({n: 5, fn: (i) => i * 3}); // returns [0, 3, 6, 9, 12]
 */
export default function rangeMap({
  n,
  fn,
}: {
  n: number;
  fn?: (i: number) => any;
}): any[] {
  const arr = [];
  while (n > arr.length) {
    if (fn) {
      arr.push(fn(arr.length));
    } else {
      arr.push(arr.length);
    }
  }
  return arr;
}
