"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _shop_header from './shop-header.bones.json'
import _shop_product_card from './shop-product-card.bones.json'

configureBoneyard({"color":"hsl(210 40% 96.1%)","darkColor":"hsl(223 47% 11%)","animate":"shimmer","shimmerColor":"rgba(255, 255, 255, 0.4)","darkShimmerColor":"rgba(255, 255, 255, 0.05)","speed":"2s","shimmerAngle":110,"stagger":80,"transition":300})

registerBones({
  "shop-header": _shop_header,
  "shop-product-card": _shop_product_card,
})
